In [1]:
import torch

print("Number of GPU: ", torch.cuda.device_count())
print("GPU Name: ", torch.cuda.get_device_name())

Number of GPU:  1
GPU Name:  NVIDIA RTX 2000 Ada Generation Laptop GPU


In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)

Using device: cuda


In [1]:
import torch

# Check if GPU is available
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("GPU is available!")
else:
    device = torch.device("cpu")
    print("GPU not available, using CPU.")

# Create two random tensors and move them to the available device (GPU or CPU)
x = torch.rand(3, 3).to(device)
y = torch.rand(3, 3).to(device)

# Perform a simple operation (matrix multiplication)
z = torch.matmul(x, y)

print("Tensor X:\n", x)
print("Tensor Y:\n", y)
print("Result of X * Y (on device):\n", z)

# Print the device of the result tensor
print(f"Result is computed on: {z.device}")


GPU is available!
Tensor X:
 tensor([[0.5418, 0.7942, 0.3699],
        [0.7762, 0.2811, 0.6000],
        [0.1728, 0.8653, 0.4661]], device='cuda:0')
Tensor Y:
 tensor([[0.1958, 0.6254, 0.1174],
        [0.0806, 0.4613, 0.5707],
        [0.6626, 0.9427, 0.8185]], device='cuda:0')
Result of X * Y (on device):
 tensor([[0.4153, 1.0539, 0.8196],
        [0.5722, 1.1807, 0.7426],
        [0.4124, 0.9466, 0.8956]], device='cuda:0')
Result is computed on: cuda:0


In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import time

# Define a simple neural network
class SimpleNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out

# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Hyperparameters
input_size = 32 * 32 * 3  # CIFAR-10 images are 32x32 with 3 color channels
hidden_size = 500
output_size = 10  # CIFAR-10 has 10 classes
num_epochs = 5
batch_size = 64
learning_rate = 0.001

# Transform to normalize the data
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

# Load CIFAR-10 dataset
train_dataset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)

# Initialize the neural network, loss function, and optimizer
model = SimpleNN(input_size, hidden_size, output_size).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Training loop
start_time = time.time()
for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0
    
    for i, (images, labels) in enumerate(train_loader):
        # Flatten the images and move them to the device (GPU or CPU)
        images = images.view(-1, 32 * 32 * 3).to(device)
        labels = labels.to(device)

        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        # Print statistics every 100 batches
        if (i + 1) % 100 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Step [{i+1}/{len(train_loader)}], Loss: {loss.item():.4f}')

end_time = time.time()
print(f"Training completed in: {end_time - start_time:.2f} seconds")

# Print the final device for the model and tensors
print(f"Model is trained on: {next(model.parameters()).device}")


Using device: cuda


100.0%


Extracting ./data\cifar-10-python.tar.gz to ./data
Epoch [1/5], Step [100/782], Loss: 1.6816
Epoch [1/5], Step [200/782], Loss: 1.6067
Epoch [1/5], Step [300/782], Loss: 1.5785
Epoch [1/5], Step [400/782], Loss: 1.5072
Epoch [1/5], Step [500/782], Loss: 1.7775
Epoch [1/5], Step [600/782], Loss: 1.5990
Epoch [1/5], Step [700/782], Loss: 1.6353
Epoch [2/5], Step [100/782], Loss: 1.5342
Epoch [2/5], Step [200/782], Loss: 1.8635
Epoch [2/5], Step [300/782], Loss: 1.5722
Epoch [2/5], Step [400/782], Loss: 1.6744
Epoch [2/5], Step [500/782], Loss: 1.3773
Epoch [2/5], Step [600/782], Loss: 1.3480
Epoch [2/5], Step [700/782], Loss: 1.3784
Epoch [3/5], Step [100/782], Loss: 1.6288
Epoch [3/5], Step [200/782], Loss: 1.3130
Epoch [3/5], Step [300/782], Loss: 1.2666
Epoch [3/5], Step [400/782], Loss: 1.3389
Epoch [3/5], Step [500/782], Loss: 1.4746
Epoch [3/5], Step [600/782], Loss: 1.3513
Epoch [3/5], Step [700/782], Loss: 1.5478
Epoch [4/5], Step [100/782], Loss: 1.2478
Epoch [4/5], Step [200/78